"""Migrate

Revision ID: 79fdcdcb6871
Revises: d47d8aba5ecc
Create Date: 2025-07-31 13:04:15.977035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79fdcdcb6871'
down_revision = 'd47d8aba5ecc'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('_password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('profile_pic', sa.VARCHAR(length=255), nullable=True),
    sa.Column('github', sa.VARCHAR(length=255), nullable=True),
    sa.Column('linkedin', sa.VARCHAR(length=255), nullable=True),
    sa.Column('skills', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('is_google_auth', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
