"""Migrate

Revision ID: befef15448ee
Revises: 79fdcdcb6871
Create Date: 2025-07-31 17:31:12.605769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'befef15448ee'
down_revision = '79fdcdcb6871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('join_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('projects', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contributions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cover_photo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cv_file', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cv_file_name', sa.String(length=255), nullable=True))
        batch_op.alter_column('profile_pic',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('skills',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('profile_pic',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('cv_file_name')
        batch_op.drop_column('cv_file')
        batch_op.drop_column('cover_photo')
        batch_op.drop_column('contributions')
        batch_op.drop_column('projects')
        batch_op.drop_column('join_date')
        batch_op.drop_column('location')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
